import { PortfolioData } from '@/types/portfolio';

export const defaultPortfolioData: PortfolioData = {
  profile: {
    name: 'Michael Aigbovbiosa',
    title: 'Senior Full Stack / AI Engineer & Mentor',
    bio: 'Highly accomplished Senior Engineer with 7+ years of experience crafting scalable web apps, Agentic AI systems, MCP tools, and high-frequency backend services with TypeScript, React, Next.js, Node.js, Python, and MongoDB.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    location: 'Lagos, Nigeria 🌍 (Remote Worldwide)',
    availability: '🟢 Available for Senior Roles, Agentic AI & Contracts',
    email: 'mikeaig4realonreal@gmail.com',
    resumeUrl: '',
    githubUrl: 'https://github.com/mikeaig4real',
    statusEmoji: '🤖',
  },
  workplaces: [
    {
      id: 'work-beeva',
      company: 'BeevaAI',
      role: 'Software Engineer (Contract)',
      period: 'Oct 2025 — Apr 2026',
      location: 'Remote (United States)',
      description: 'Implemented 3rd-party cosmetic SDK workflows, enhanced security middleware, improved API type-safety, and built the business application dashboard & product management module.',
      skills: ['React', 'React Router', 'Node.js', 'Python', 'FastAPI', 'TypeScript'],
      isCurrent: false,
      logoBg: '#facc15', // Yellow
    },
    {
      id: 'work-springboard',
      company: 'Springboard',
      role: 'Software Engineering Mentor',
      period: 'Dec 2022 — Present',
      location: 'Remote (United States)',
      description: 'Mentoring aspiring engineers in Full Stack development, Data Structures, Algorithms, Python, Flask, SQL, and React. Conducting 1-on-1 career assistance and code reviews.',
      skills: ['React', 'Node.js', 'Express', 'Python', 'Flask', 'SQL', 'Algorithms'],
      isCurrent: true,
      logoBg: '#70d6ff', // Neon Cyan
    },
    {
      id: 'work-happierleads',
      company: 'HappierLeads',
      role: 'Full Stack Engineer',
      period: 'May 2023 — Aug 2023',
      location: 'Remote (United Kingdom)',
      description: 'Built client-side prospectus editor, AI visitor intention summarizer, and automated email workflows (reducing manual work by 30%). Reduced server round trip by 45% via query optimization.',
      skills: ['Next.js', 'React', 'Redux Saga', 'Node.js', 'MongoDB', 'Mongoose'],
      isCurrent: false,
      logoBg: '#ff70a6', // Hot Pink
    },
    {
      id: 'work-micserah',
      company: 'Micserah / BetRelate',
      role: 'Senior Backend Engineer',
      period: 'Feb 2022 — Apr 2024',
      location: 'Remote (Nigeria)',
      description: 'Refactored Express monolith to Nest.js microservices. Engineered real-time chat engines, competitions, leaderboards, and GCP queue processing (+50% user engagement).',
      skills: ['Node.js', 'Nest.js', 'Express', 'TypeScript', 'MongoDB', 'Socket.io', 'Redis', 'BullMQ', 'Docker'],
      isCurrent: false,
      logoBg: '#a7f3d0', // Lime
    },
    {
      id: 'work-blockchainlabs',
      company: 'Blockchain Labs',
      role: 'Senior Full Stack Engineer',
      period: 'Apr 2022 — Mar 2023',
      location: 'Hybrid (Nigeria)',
      description: 'Designed microservices architecture, CI/CD pipeline on Heroku + GitHub Actions, and Nginx load balancing to double request capacity (2x RPM).',
      skills: ['Node.js', 'Express', 'MongoDB', 'IPFS', 'Nginx', 'Tailwind', 'Heroku', 'Cypress'],
      isCurrent: false,
      logoBg: '#d8b4fe', // Purple
    },
    {
      id: 'work-rygma',
      company: 'Rygma Solutions',
      role: 'Full Stack Engineer (Freelance)',
      period: 'Jan 2018 — Jan 2022',
      location: 'Hybrid (Nigeria)',
      description: 'Engineered 3-component SaaS examination software, local area network HTTP servers, and dynamic D3 data visualization dashboards.',
      skills: ['React', 'React Native', 'Node.js', 'TypeScript', 'PostgreSQL', 'MongoDB', 'AWS', 'D3.js'],
      isCurrent: false,
      logoBg: '#ff9f1c', // Orange
    },
  ],
  projects: [
    {
      id: 'proj-bug-exterminator',
      title: 'Bug Exterminator',
      tagline: 'Interactive coding & bug-fixing practice app',
      description: 'An interactive playground for developers to test, diagnose, and exterminate complex JavaScript/TypeScript bugs in real-time.',
      category: 'Web App',
      tags: ['React', 'TypeScript', 'Tailwind CSS', 'Vercel'],
      viewType: 'featured',
      coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=1200&q=80',
      ],
      demoUrl: 'https://bug-exterminator.vercel.app',
      githubUrl: 'https://github.com/mikeaig4real',
      metric: {
        label: 'Coding Challenges',
        value: '100+ Fixes',
      },
      featured: true,
      accentColor: '#facc15',
    },
    {
      id: 'proj-brain-q',
      title: 'Brain-Q Cognitive App',
      tagline: 'Gamified brain fitness & memory training platform',
      description: 'Challenge your cognitive agility, memory retention, and problem-solving speed with real-time score tracking and analytics.',
      category: 'EdTech / Game',
      tags: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript'],
      viewType: 'gallery',
      coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=1000&q=80',
      ],
      demoUrl: 'https://brain-q.vercel.app',
      githubUrl: 'https://github.com/mikeaig4real',
      featured: true,
      accentColor: '#ff70a6',
    },
    {
      id: 'proj-snipify',
      title: 'Snipify AI Summarizer',
      tagline: 'Extract ultra-dense summaries from massive text blocks',
      description: 'Lightweight AI text processing utility that distills articles, documents, and technical logs into actionable snippets.',
      category: 'AI Utility',
      tags: ['TypeScript', 'FastAPI', 'OpenAI SDK', 'Model Context Protocol'],
      viewType: 'code',
      coverImage: '',
      galleryImages: [],
      demoUrl: 'https://github.com/mikeaig4real/snipify',
      githubUrl: 'https://github.com/mikeaig4real/snipify',
      codeSnippet: {
        language: 'typescript',
        code: `import { FastMCP, Agent } from '@modelcontextprotocol/sdk';\n\nconst snipifyAgent = new Agent({\n  model: 'gpt-4o',\n  systemPrompt: 'Summarize text into brutalist key bullet points.'\n});\n\nexport const snipText = async (text: string) => {\n  return await snipifyAgent.run({ input: text });\n};`,
      },
      featured: false,
      accentColor: '#70d6ff',
    },
    {
      id: 'proj-video-hub',
      title: 'Video Hub Platform',
      tagline: 'High-speed video management, encoding & React player UI',
      description: 'Modern video showcase dashboard supporting chunked file uploads, custom player skins, category organization, and streaming.',
      category: 'Full Stack App',
      tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
      viewType: 'metric',
      coverImage: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=800&q=80',
      galleryImages: [],
      demoUrl: 'https://github.com/mikeaig4real/video_upload_react_ui',
      githubUrl: 'https://github.com/mikeaig4real/video_upload_react_ui',
      metric: {
        label: 'Video Upload Speed',
        value: '< 2.5s Load',
      },
      featured: false,
      accentColor: '#a7f3d0',
    },
  ],
  skills: [
    {
      id: 'skill-fe',
      category: 'Frontend & UI Frameworks',
      skills: ['TypeScript', 'React', 'Next.js', 'Vue', 'Tailwind CSS', 'Framer Motion', 'Redux Toolkit/Saga', 'Three.js', 'D3.js', 'GraphQL'],
      badgeColor: '#facc15',
    },
    {
      id: 'skill-be',
      category: 'Backend & Agentic AI',
      skills: ['Node.js', 'Express', 'Nest.js', 'Python', 'FastAPI', 'Pydantic', 'OpenAI Agents SDK', 'LangChain', 'LiteLLM', 'Model Context Protocol (MCP)', 'Socket.io', 'BullMQ', 'RabbitMQ'],
      badgeColor: '#70d6ff',
    },
    {
      id: 'skill-db',
      category: 'Databases & Vector Search',
      skills: ['MongoDB / Mongoose', 'PostgreSQL', 'Redis', 'ChromaDB', 'pgvector', 'SQLite', 'MySQL'],
      badgeColor: '#a7f3d0',
    },
    {
      id: 'skill-cloud',
      category: 'Cloud, Testing & DevOps',
      skills: ['AWS', 'GCP', 'DigitalOcean', 'Docker', 'Git / GitHub Actions', 'Jest', 'Vitest', 'Cypress', 'Postman'],
      badgeColor: '#ff70a6',
    },
  ],
  socials: [
    { id: 'soc-gh', platform: 'GitHub', url: 'https://github.com/mikeaig4real', username: '@mikeaig4real' },
    { id: 'soc-li', platform: 'LinkedIn', url: 'https://linkedin.com/in/michael-aigbovbiosa-ba5a79105', username: 'Michael Aigbovbiosa' },
    { id: 'soc-tw', platform: 'Twitter', url: 'https://twitter.com/mikeaig4real', username: '@mikeaig4real' },
    { id: 'soc-em', platform: 'Email', url: 'mailto:mikeaig4realonreal@gmail.com', username: 'mikeaig4realonreal@gmail.com' },
  ],
  cards: [
    {
      id: 'card-hero',
      type: 'hero_profile',
      title: 'Profile & Avatar',
      colSpan: 2,
      rowSpan: 2,
      order: 1,
      visible: true,
      accentColor: '#facc15',
    },
    {
      id: 'card-workplace',
      type: 'workplace',
      title: 'Professional Experience',
      colSpan: 2,
      rowSpan: 1,
      order: 2,
      visible: true,
      accentColor: '#ff70a6',
    },
    {
      id: 'card-proj-1',
      type: 'featured_project',
      title: 'Flagship Project: Bug Exterminator',
      targetId: 'proj-bug-exterminator',
      colSpan: 2,
      rowSpan: 2,
      order: 3,
      visible: true,
      accentColor: '#70d6ff',
    },
    {
      id: 'card-proj-2',
      type: 'project_view',
      title: 'Brain-Q App',
      targetId: 'proj-brain-q',
      colSpan: 2,
      rowSpan: 1,
      order: 4,
      visible: true,
      accentColor: '#a7f3d0',
    },
    {
      id: 'card-socials',
      type: 'socials',
      title: 'Connect & Links',
      colSpan: 1,
      rowSpan: 1,
      order: 5,
      visible: true,
      accentColor: '#d8b4fe',
    },
    {
      id: 'card-tech-stack',
      type: 'tech_stack',
      title: 'Skills & AI Ecosystem',
      colSpan: 2,
      rowSpan: 2,
      order: 6,
      visible: true,
      accentColor: '#facc15',
    },
    {
      id: 'card-proj-3',
      type: 'project_view',
      title: 'Snipify AI',
      targetId: 'proj-snipify',
      colSpan: 2,
      rowSpan: 1,
      order: 7,
      visible: true,
      accentColor: '#ff9f1c',
    },
    {
      id: 'card-proj-4',
      type: 'project_view',
      title: 'Video Hub',
      targetId: 'proj-video-hub',
      colSpan: 1,
      rowSpan: 1,
      order: 8,
      visible: true,
      accentColor: '#70d6ff',
    },
    {
      id: 'card-note',
      type: 'custom_note',
      title: 'AI Certifications & Track',
      colSpan: 1,
      rowSpan: 1,
      order: 9,
      visible: true,
      accentColor: '#a7f3d0',
      customContent: {
        title: '🤖 Andela Certified AI Engineer',
        body: 'Production LLMs, Agentic AI, MCP Server Architecture & Vector Databases (ChromaDB, pgvector).',
        metricValue: '7+ Yrs',
        metricLabel: 'Senior Full Stack Experience',
      },
    },
  ],
};
