'use client';

import React from 'react';
import { Copy, Check, CheckCircle2 } from 'lucide-react';
import { generateRISENPrompt } from '@/lib/ai/prompts';

interface RisenPromptTabProps {
  resumeText: string;
  pastedJson: string;
  setPastedJson: (val: string) => void;
  copiedPrompt: boolean;
  setCopiedPrompt: (val: boolean) => void;
  onValidate: () => void;
}

export const RisenPromptTab: React.FC<RisenPromptTabProps> = ({
  resumeText,
  pastedJson,
  setPastedJson,
  copiedPrompt,
  setCopiedPrompt,
  onValidate,
}) => {
  const handleCopyRISENPrompt = () => {
    const promptText = generateRISENPrompt(resumeText || '[PASTE YOUR RESUME TEXT HERE]');
    navigator.clipboard.writeText(promptText);
    setCopiedPrompt(true);
    setTimeout(() => setCopiedPrompt(false), 2500);
  };

  return (
    <div className="space-y-4 font-mono">
      <div className="p-3 bg-yellow-100 dark:bg-slate-800 border-2 border-black dark:border-white text-xs space-y-2">
        <p className="font-bold text-black dark:text-white">
          📋 RISEN Pattern Exporter (For ChatGPT, Claude, or Gemini):
        </p>
        <p className="text-slate-700 dark:text-slate-300">
          Copy our pre-formatted RISEN pattern prompt pre-injected with our Zod JSON schema structure. Paste it into your preferred LLM and copy back the generated JSON!
        </p>
        <button
          onClick={handleCopyRISENPrompt}
          className="px-3 py-1.5 bg-black text-yellow-300 border border-white font-extrabold text-xs uppercase flex items-center gap-1.5 cursor-pointer shadow-[2px_2px_0px_0px_#000]"
        >
          {copiedPrompt ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          <span>{copiedPrompt ? 'Prompt Copied!' : 'Copy RISEN Pattern Prompt'}</span>
        </button>
      </div>

      <div>
        <label className="block text-xs font-extrabold uppercase mb-1 text-black dark:text-white">
          Paste Generated Portfolio JSON:
        </label>
        <textarea
          value={pastedJson}
          onChange={(e) => setPastedJson(e.target.value)}
          placeholder="Paste raw JSON object generated by AI here..."
          className="w-full h-32 p-3 bg-slate-100 dark:bg-slate-800 border-2 border-black dark:border-white font-mono text-xs outline-none text-black dark:text-white"
        />
      </div>

      <button
        onClick={onValidate}
        className="w-full py-3 bg-cyan-300 hover:bg-cyan-400 text-black font-extrabold text-xs uppercase border-3 border-black shadow-[4px_4px_0px_0px_#000] flex items-center justify-center gap-2 cursor-pointer"
      >
        <CheckCircle2 className="w-4 h-4 stroke-[2.5]" />
        <span>Validate & Hydrate Portfolio JSON</span>
      </button>
    </div>
  );
};
